language: java
jdk:
- oraclejdk9
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: lKnrx9R7j97utCnGBUSAXSKgzgmBTOs6XYeLMrCW+jFSZK0PIdyE2ZhiJbsxdtTGKpQ0oOGccJB9fiVvjsAu6LiyhtShVM3BaHpuomPzL+0STZGoEUi/VzBpqIEbYYSylcx8oYJrGcImhgBwY2NA0ZeEvboqY9Cb4FV79B6qH3oI1VRGEcACcEX/jIFMG1xsJE2xZKEcQD6TbZJEzH1gTQlo7wHTnlCSNpMEgXJmJSr9Nl+i1P1GOYOkEDqGAR1qcPWsE0o8D1R8x4luZuH0y3YgSmiCSXlP66MWuS4tK5QqTPJ5nINDOBJwk0SAg/Qjke/JUPm4Ah3uWq0OMIQ/eZq94PjiIY4kYeh3Y5WAPTcuHLTjRKfy/Te+nzybjbm9gzIPF4rW0u/WthLslLpXB5o57PGBCDw8JDE1biLhqc+3WA8lCSYPOFqrOj+0rlKZxUDDy/1zdSiYJtXaRJGncIDCfuenRakr3abeUxfyjnSWwh1uzU7g/b25o8/qjMgmc6GkRBz2s0wwmRkH5Jp/wt0ywi/2bVmsKXfj/unc8F3S0RhkepzJieIVf7KixH4jC2KTNUQys2D5u447PQXo+JmwAqWafSAseqobBDAlaHLo7bqfudTroDaeYkeJzEHSP+IEUgtv+kD5EGMRZDfaioO+QFa/eP4XRoFkhKELfIw=

script: mvn clean verify --settings travis-settings.xml -Dgpg.passphrase=upwork
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B -Dgpg.passphrase=upwork
