language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=leonarduk
  - secure: AvSpurKBzeTe3KWSlMrfRJjVi6Vx5Agz4453WhzVhGTQXU+kDHgKknXM+0dfPKXXat59Wvd3PXhs8i0KgpUDt3gc8bZ3ENGPMHdtUWlEG+5upFottOoz+M/WmsEK7jVWkdaY8xeSG0Tke/bZih21DYvR9Daeai4VOMYrJYbT27v8CGi8X0e8spGdJRqDkrZKCKve2JQlh6zJ9ofVG1HHredX3yGbvKgAWkWYjKpW3tEcMzLA5G9w37AWnh3zj9GiqC6PU/i9TIhy+WpQS23wcoTzaGynsfl2xHthYl43fwCSSkyse6qX1A6PaJmzvGh02uILV0ehsezyeqFWGQUCxJztDtBrfE6We2h9o0WYaMP1qmYqmJ5IeFhrOGzh1oE/DEGv4EJW4fDgS8HuW5ri6JLgL+UQ7pmQsBm2ZFcD7G09kwfVDQVoCpYp1TQd/04CMgnzwxj1wNawSvzUbwrN3UCsOEYAmElGljl0U4LmVEUqAJBNyNoMn2n94G7kv1bDPrz1JobuDCIFIh0HBt0mtgdd5gfFM0v9qPY4sP2i2MUue2fNryYuK2lpAa32WaPQwzEC635eEqCL/QZNkan2NYAd++PoQHJJjEb8B94iyAFXOMPL9D1vEyTIIulYJCEBZgM680Yxcz9xEvFldPcZ5JeCXofhnjBOxl9Z8acowDs=
script: mvn clean verify
after_success:
- bash <(curl -s https://codecov.io/bash)
- mvn deploy --settings travis-settings.xml -DskipTests=true -B
